### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BujiXI** [bjuonday/Modified-ProTanki#2]
So i replaced the application.xml and then when i launched the game it says "Connection error!"
![Screenshot (246)](https://github.com/bjuonday/Modified-ProTanki/assets/138483064/1c19829c-60b3-4705-b074-6ed6a1305f17)

**Comment by bjuonday** [comment]
Outdated prelauncher as it seems. Will fix as soon as possible.

**Comment by bjuonday** [comment]
Replace it with modified one again and see if it works.

**Comment by bjuonday** [comment]
-aand it's fixed, I guess.
