### ISSUE TITLE
hey, i know this isnt really an issue but can you make this library.swf have the updated supply icons too?

### ISSUE THREAD

**Issue by FatalDiscovery** [bjuonday/Modified-ProTanki#3]
https://web.archive.org/web/20220929113606oe_/http://s2.protanki-online.com/library.swf
this one. im 100% understanding if youre too lazy lol

**Comment by bjuonday** [comment]
ok :) | link: [library.zip](https://github.com/user-attachments/files/15525866/library.zip) << i hope i made that buy button icon resized properly without ever launching it
and yes, i'm lazy due to their constant library changes up and recently

**Comment by FatalDiscovery** [comment]
🤝 thanks bro
